migrate(
  (app) => {
    // 1. Create collection implementation_checklist
    if (!app.hasTable('implementation_checklist')) {
      const collection = new Collection({
        name: 'implementation_checklist',
        type: 'base',
        listRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
        createRule: "@request.auth.id != ''",
        updateRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          { name: 'item_key', type: 'text', required: true },
          { name: 'phase_id', type: 'number', required: true, onlyInt: true },
          { name: 'phase_title', type: 'text', required: true },
          { name: 'title', type: 'text', required: true },
          { name: 'how_to', type: 'text' },
          { name: 'expected_result', type: 'text' },
          { name: 'attention_alert', type: 'text' },
          { name: 'is_highlight', type: 'bool' },
          { name: 'order_index', type: 'number', onlyInt: true },
          { name: 'done', type: 'bool' },
          { name: 'done_by', type: 'text' },
          { name: 'done_at', type: 'date' },
          { name: 'notes', type: 'text' },
          { name: 'failure_registered', type: 'bool' },
          { name: 'failure_description', type: 'text' },
          { name: 'failure_date', type: 'date' },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
        indexes: [
          'CREATE UNIQUE INDEX idx_impl_chk_item_key ON implementation_checklist (item_key)',
          'CREATE INDEX idx_impl_chk_phase ON implementation_checklist (phase_id)',
          'CREATE INDEX idx_impl_chk_done ON implementation_checklist (done)',
        ],
      })
      app.save(collection)
    }

    const col = app.findCollectionByNameOrId('implementation_checklist')

    // 2. Pre-seed all items from the implementation checklist roadmap
    const seedItems = [
      // FASE 0 — Preparação (½ dia)
      {
        item_key: '0.1',
        phase_id: 0,
        phase_title: 'FASE 0 — Preparação (½ dia)',
        title: 'Acessos da equipe',
        how_to: 'Cada membro da GQ faz login com o e-mail corporativo',
        expected_result: 'Todos entram sem erro.',
        attention_alert: '',
        is_highlight: false,
        order_index: 1,
      },
      {
        item_key: '0.2',
        phase_id: 0,
        phase_title: 'FASE 0 — Preparação (½ dia)',
        title: 'Verificar permissões',
        how_to: 'Cada um abre todos os menus',
        expected_result: 'Cada papel vê só o que deve (GQ vê tudo; operador vê o básico).',
        attention_alert: '',
        is_highlight: false,
        order_index: 2,
      },
      {
        item_key: '0.3',
        phase_id: 0,
        phase_title: 'FASE 0 — Preparação (½ dia)',
        title: 'Cadastrar/validar empresas',
        how_to: 'Conferir PSC, Koala System e GenTi',
        expected_result: '3 empresas ativas.',
        attention_alert: '',
        is_highlight: false,
        order_index: 3,
      },
      {
        item_key: '0.4',
        phase_id: 0,
        phase_title: 'FASE 0 — Preparação (½ dia)',
        title: 'Revisar cadastro de colaboradores',
        how_to: 'Cargos, áreas e vínculos com usuários',
        expected_result: 'Ninguém "órfão" (colaborador sem usuário).',
        attention_alert: '',
        is_highlight: false,
        order_index: 4,
      },

      // FASE 1 — Documentos (base de tudo)
      {
        item_key: '1.1',
        phase_id: 1,
        phase_title: 'FASE 1 — Documentos (base de tudo)',
        title: 'Upload de documento',
        how_to: 'Subir 1 procedimento real (ex.: FSGQ 8.7-2) com código, revisão e vigência',
        expected_result: 'Aparece na listagem com a revisão correta.',
        attention_alert: '',
        is_highlight: false,
        order_index: 5,
      },
      {
        item_key: '1.2',
        phase_id: 1,
        phase_title: 'FASE 1 — Documentos (base de tudo)',
        title: 'Repasse de leitura',
        how_to: 'Designar 3 colaboradores para ler um documento',
        expected_result: 'Eles aparecem como "pendentes de leitura".',
        attention_alert: '',
        is_highlight: false,
        order_index: 6,
      },
      {
        item_key: '1.3',
        phase_id: 1,
        phase_title: 'FASE 1 — Documentos (base de tudo)',
        title: 'Registro de sessão de leitura',
        how_to: 'Um dos 3 lê o documento no sistema',
        expected_result: 'Tempo de leitura e data registrados.',
        attention_alert: '',
        is_highlight: false,
        order_index: 7,
      },
      {
        item_key: '1.4',
        phase_id: 1,
        phase_title: 'FASE 1 — Documentos (base de tudo)',
        title: 'Quiz de verificação',
        how_to: 'Responder o questionário do documento',
        expected_result: 'Aprovado/reprovado conforme acertos.',
        attention_alert: '',
        is_highlight: false,
        order_index: 8,
      },
      {
        item_key: '1.5',
        phase_id: 1,
        phase_title: 'FASE 1 — Documentos (base de tudo)',
        title: 'Nova revisão',
        how_to: 'Publicar a rev. 02 de um documento já lido',
        expected_result: 'Status de leitura zera e volta a pendente.',
        attention_alert: '',
        is_highlight: false,
        order_index: 9,
      },
      {
        item_key: '1.6',
        phase_id: 1,
        phase_title: 'FASE 1 — Documentos (base de tudo)',
        title: 'Homologação dos 6 templates',
        how_to: 'GQ confere os templates contra os formulários oficiais',
        expected_result: 'Vocabulário idêntico ao FSGQ.',
        attention_alert: '',
        is_highlight: false,
        order_index: 10,
      },

      // FASE 2 — Checklists
      {
        item_key: '2.1',
        phase_id: 2,
        phase_title: 'FASE 2 — Checklists',
        title: 'Criar checklist de inspeção',
        how_to: 'Montar 1 checklist com 10 itens, vinculado a cargo e processo',
        expected_result: 'Salvo e visível para o cargo certo.',
        attention_alert: '',
        is_highlight: false,
        order_index: 11,
      },
      {
        item_key: '2.2',
        phase_id: 2,
        phase_title: 'FASE 2 — Checklists',
        title: 'Preenchimento pelo operador',
        how_to: 'Um apontador preenche o checklist em uma OS',
        expected_result: 'Registro com data, itens C/NC e fotos.',
        attention_alert: '',
        is_highlight: false,
        order_index: 12,
      },
      {
        item_key: '2.3',
        phase_id: 2,
        phase_title: 'FASE 2 — Checklists',
        title: 'Tratamento de NC do checklist',
        how_to: 'Reprovar um item e verificar o encaminhamento',
        expected_result: 'NC aparece para a GQ (origem correta).',
        attention_alert: '',
        is_highlight: false,
        order_index: 13,
      },
      {
        item_key: '2.4',
        phase_id: 2,
        phase_title: 'FASE 2 — Checklists',
        title: 'Relatório de conformidade',
        how_to: 'Abrir o resumo do checklist preenchido',
        expected_result: '% de conformidade e itens reprovados corretos.',
        attention_alert: '',
        is_highlight: false,
        order_index: 14,
      },

      // FASE 3 — Treinamentos
      {
        item_key: '3.1',
        phase_id: 3,
        phase_title: 'FASE 3 — Treinamentos',
        title: 'Plano anual',
        how_to: 'Cadastrar 3 treinamentos do plano 2026 com carga e público',
        expected_result: 'Aparecem no calendário/plano.',
        attention_alert: '',
        is_highlight: false,
        order_index: 15,
      },
      {
        item_key: '3.2',
        phase_id: 3,
        phase_title: 'FASE 3 — Treinamentos',
        title: 'Execução com lista de presença',
        how_to: 'Registrar 1 treinamento realizado com presença e nota',
        expected_result: 'Participantes atualizados.',
        attention_alert: '',
        is_highlight: false,
        order_index: 16,
      },
      {
        item_key: '3.3',
        phase_id: 3,
        phase_title: 'FASE 3 — Treinamentos',
        title: 'Avaliação de eficácia',
        how_to: 'Após o treinamento, avaliar eficácia (reavaliação)',
        expected_result: 'Eficaz/Ineficaz registrado.',
        attention_alert: '',
        is_highlight: false,
        order_index: 17,
      },
      {
        item_key: '3.4',
        phase_id: 3,
        phase_title: 'FASE 3 — Treinamentos',
        title: 'Indicador de cobertura',
        how_to: 'Abrir o painel de treinamentos',
        expected_result: '% treinado por cargo/processo confere.',
        attention_alert: '',
        is_highlight: false,
        order_index: 18,
      },

      // FASE 4 — RNC (o coração — fazer com cuidado)
      {
        item_key: '4.1',
        phase_id: 4,
        phase_title: 'FASE 4 — RNC (o coração — fazer com cuidado)',
        title: 'Importação controle 2025',
        how_to: 'Assistente de importação, empresa PSC, planilha de controle 2025',
        expected_result: 'Preview mostra "Aba: CONTROLE_RNC" com as linhas reais; grava sem lixo.',
        attention_alert:
          'Se falhar, não reimportar por tentativa e erro — registrar o que apareceu no preview e acionar o Skip em modo Agente.',
        is_highlight: true,
        order_index: 19,
      },
      {
        item_key: '4.2',
        phase_id: 4,
        phase_title: 'FASE 4 — RNC (o coração — fazer com cuidado)',
        title: 'Importação controle 2026',
        how_to: 'Mesmo processo',
        expected_result: 'Total 81 RNCs PSC no sistema.',
        attention_alert:
          'Se falhar, não reimportar por tentativa e erro — registrar o que apareceu no preview e acionar o Skip em modo Agente.',
        is_highlight: true,
        order_index: 20,
      },
      {
        item_key: '4.3',
        phase_id: 4,
        phase_title: 'FASE 4 — RNC (o coração — fazer com cuidado)',
        title: 'Enriquecimento (8.7-2)',
        how_to: 'Arrastar os Excel individuais juntos',
        expected_result: '5 Porquês, Ishikawa e evidências mesclados pelo número.',
        attention_alert: '',
        is_highlight: false,
        order_index: 21,
      },
      {
        item_key: '4.4',
        phase_id: 4,
        phase_title: 'FASE 4 — RNC (o coração — fazer com cuidado)',
        title: 'Importação Koala',
        how_to: 'Repetir 4.1–4.3 (35 RNCs)',
        expected_result: 'Contagem e status conferidos.',
        attention_alert: '',
        is_highlight: false,
        order_index: 22,
      },
      {
        item_key: '4.5',
        phase_id: 4,
        phase_title: 'FASE 4 — RNC (o coração — fazer com cuidado)',
        title: 'Validação em bloco',
        how_to:
          'Chamar o Skip para validar no banco (contagem por ano, datas, origens, amostragem)',
        expected_result: 'Relatório de validação aprovado.',
        attention_alert: '',
        is_highlight: false,
        order_index: 23,
      },
      {
        item_key: '4.6',
        phase_id: 4,
        phase_title: 'FASE 4 — RNC (o coração — fazer com cuidado)',
        title: 'Nova RNC manual',
        how_to:
          'Emitir 1 RNC de teste com todos os campos FSGQ 8.7-2 (3 flags, tipo de ação, grau, causa raiz, avaliação de risco)',
        expected_result: 'Formulário completo aceito, numeração automática.',
        attention_alert: '',
        is_highlight: false,
        order_index: 24,
      },
      {
        item_key: '4.7',
        phase_id: 4,
        phase_title: 'FASE 4 — RNC (o coração — fazer com cuidado)',
        title: 'Ciclo completo da RNC',
        how_to: 'Correção imediata → causa raiz → ação → reinspeção → verificação de eficácia',
        expected_result: 'Status muda corretamente; se ineficaz, abre campo de nova RNC.',
        attention_alert: '',
        is_highlight: false,
        order_index: 25,
      },
      {
        item_key: '4.8',
        phase_id: 4,
        phase_title: 'FASE 4 — RNC (o coração — fazer com cuidado)',
        title: 'Dashboard e CNQ',
        how_to: 'Conferir IRPI/INCF e o relatório de Custo da Não Qualidade',
        expected_result: 'Números batem com a planilha de controle (amostragem de 5 RNCs).',
        attention_alert: '',
        is_highlight: false,
        order_index: 26,
      },
      {
        item_key: '4.9',
        phase_id: 4,
        phase_title: 'FASE 4 — RNC (o coração — fazer com cuidado)',
        title: 'Exportação CSV',
        how_to: 'Exportar o detalhamento de custo',
        expected_result: 'Abre no Excel com pt-BR correto.',
        attention_alert: '',
        is_highlight: false,
        order_index: 27,
      },

      // FASE 5 — Riscos e Auditorias
      {
        item_key: '5.1',
        phase_id: 5,
        phase_title: 'FASE 5 — Riscos e Auditorias',
        title: 'Workshop de riscos',
        how_to: 'Sessão com responsáveis de processo; cadastrar 10-15 riscos com P×I',
        expected_result: 'Matriz 5×5 preenchida e colorida.',
        attention_alert: '',
        is_highlight: false,
        order_index: 28,
      },
      {
        item_key: '5.2',
        phase_id: 5,
        phase_title: 'FASE 5 — Riscos e Auditorias',
        title: 'Plano de tratamento',
        how_to: 'Atribuir responsável e prazo a 3 riscos altos/críticos',
        expected_result: 'Status "Planejado" com vencimento no painel.',
        attention_alert: '',
        is_highlight: false,
        order_index: 29,
      },
      {
        item_key: '5.3',
        phase_id: 5,
        phase_title: 'FASE 5 — Riscos e Auditorias',
        title: 'Programa de auditorias 2026',
        how_to: 'Cadastrar auditorias por processo com datas e auditores',
        expected_result: 'Grade anual com % de execução.',
        attention_alert: '',
        is_highlight: false,
        order_index: 30,
      },
      {
        item_key: '5.4',
        phase_id: 5,
        phase_title: 'FASE 5 — Riscos e Auditorias',
        title: 'Teste do semáforo',
        how_to: 'Cadastrar 1 auditoria com data prevista já passada',
        expected_result: 'Fica vermelha (Atrasada) automaticamente.',
        attention_alert: '',
        is_highlight: false,
        order_index: 31,
      },
      {
        item_key: '5.5',
        phase_id: 5,
        phase_title: 'FASE 5 — Riscos e Auditorias',
        title: 'Regra de independência',
        how_to: 'Escolher auditor do próprio processo auditado',
        expected_result: 'Sistema alerta na hora.',
        attention_alert: '',
        is_highlight: false,
        order_index: 32,
      },
      {
        item_key: '5.6',
        phase_id: 5,
        phase_title: 'FASE 5 — Riscos e Auditorias',
        title: 'Auditoria piloto',
        how_to:
          'Executar 1 auditoria real (sugestão: PCP ou Expedição) com checklist C/NC/N.A. e evidências',
        expected_result: 'Relatório gerado automaticamente, pronto para PDF.',
        attention_alert: '',
        is_highlight: false,
        order_index: 33,
      },
      {
        item_key: '5.7',
        phase_id: 5,
        phase_title: 'FASE 5 — Riscos e Auditorias',
        title: 'Achado → RNC',
        how_to: 'Registrar 1 achado NC e aceitar a criação da RNC vinculada',
        expected_result: 'RNC criada com origem "Auditorias" e vínculo bidirecional.',
        attention_alert: '',
        is_highlight: false,
        order_index: 34,
      },

      // FASE 6 — Objetivos e Revisão pela Direção
      {
        item_key: '6.1',
        phase_id: 6,
        phase_title: 'FASE 6 — Objetivos e Revisão pela Direção',
        title: 'Objetivos 2026',
        how_to:
          'Cadastrar objetivos com indicador, meta, linha de base e responsável (por processo)',
        expected_result: '% de atingimento e semáforo corretos.',
        attention_alert: '',
        is_highlight: false,
        order_index: 35,
      },
      {
        item_key: '6.2',
        phase_id: 6,
        phase_title: 'FASE 6 — Objetivos e Revisão pela Direção',
        title: 'Plano de ação do objetivo',
        how_to: 'Adicionar 2-3 ações por objetivo',
        expected_result: 'Expansível na tabela, com status.',
        attention_alert: '',
        is_highlight: false,
        order_index: 36,
      },
      {
        item_key: '6.3',
        phase_id: 6,
        phase_title: 'FASE 6 — Objetivos e Revisão pela Direção',
        title: 'Consolidação automática',
        how_to: 'Na Revisão pela Direção, clicar em consolidar',
        expected_result:
          'Entradas pré-preenchidas com dados reais do ano (RNCs, custos, auditorias, riscos, treinamentos, objetivos, IRPI/INCF).',
        attention_alert: '',
        is_highlight: false,
        order_index: 37,
      },
      {
        item_key: '6.4',
        phase_id: 6,
        phase_title: 'FASE 6 — Objetivos e Revisão pela Direção',
        title: 'Ata da reunião',
        how_to: 'Preencher saídas do §9.3 e ações deliberadas; gerar ata em PDF',
        expected_result: 'PDF com tabelas e campos de assinatura.',
        attention_alert: '',
        is_highlight: false,
        order_index: 38,
      },
      {
        item_key: '6.5',
        phase_id: 6,
        phase_title: 'FASE 6 — Objetivos e Revisão pela Direção',
        title: 'Primeira Revisão pela Direção real',
        how_to: 'Agendar com o Diretor usando o material consolidado',
        expected_result: 'Ata assinada — marco de maturidade do SGQ.',
        attention_alert:
          '🔥 Marco de maturidade — primeira Revisão pela Direção real com ata assinada pelo Diretor.',
        is_highlight: true,
        order_index: 39,
      },

      // FASE 7 — Semana de lançamento (segunda-feira dos colaboradores)
      {
        item_key: '7.1',
        phase_id: 7,
        phase_title: 'FASE 7 — Semana de lançamento (segunda-feira dos colaboradores)',
        title: 'Treinamento relâmpago: como ler documento + responder quiz',
        how_to: 'GQ realiza com as turmas',
        expected_result: '30 min por turma.',
        attention_alert: '',
        is_highlight: false,
        order_index: 40,
      },
      {
        item_key: '7.2',
        phase_id: 7,
        phase_title: 'FASE 7 — Semana de lançamento (segunda-feira dos colaboradores)',
        title: 'Como preencher checklist de OS',
        how_to: 'Treinamento focado para Apontadores',
        expected_result: '20 min.',
        attention_alert: '',
        is_highlight: false,
        order_index: 41,
      },
      {
        item_key: '7.3',
        phase_id: 7,
        phase_title: 'FASE 7 — Semana de lançamento (segunda-feira dos colaboradores)',
        title: 'Como emitir/consultar RNC',
        how_to: 'Treinamento prático para Supervisores',
        expected_result: '30 min.',
        attention_alert: '',
        is_highlight: false,
        order_index: 42,
      },
      {
        item_key: '7.4',
        phase_id: 7,
        phase_title: 'FASE 7 — Semana de lançamento (segunda-feira dos colaboradores)',
        title: 'Acompanhamento diário na primeira semana',
        how_to: 'GQ monitora ativamente a operação',
        expected_result: 'GQ registra dúvidas como itens do roteiro.',
        attention_alert: '',
        is_highlight: false,
        order_index: 43,
      },
      {
        item_key: '7.5',
        phase_id: 7,
        phase_title: 'FASE 7 — Semana de lançamento (segunda-feira dos colaboradores)',
        title: 'Balanço da 1ª semana',
        how_to: 'Leituras realizadas, checklists preenchidos, RNCs emitidas',
        expected_result: 'GQ → Skip para ajustes.',
        attention_alert: '',
        is_highlight: false,
        order_index: 44,
      },
    ]

    for (let i = 0; i < seedItems.length; i++) {
      const item = seedItems[i]
      try {
        const existing = app.findRecordsByFilter(
          'implementation_checklist',
          `item_key = '${item.item_key}'`,
          '',
          1,
          0,
        )
        if (existing.length === 0) {
          const record = new Record(col)
          record.set('item_key', item.item_key)
          record.set('phase_id', item.phase_id)
          record.set('phase_title', item.phase_title)
          record.set('title', item.title)
          record.set('how_to', item.how_to)
          record.set('expected_result', item.expected_result)
          record.set('attention_alert', item.attention_alert)
          record.set('is_highlight', item.is_highlight)
          record.set('order_index', item.order_index)
          record.set('done', false)
          record.set('done_by', '')
          record.set('notes', '')
          record.set('failure_registered', false)
          record.set('failure_description', '')
          app.save(record)
        }
      } catch (err) {
        console.log('Error seeding item ' + item.item_key + ': ' + err)
      }
    }
  },
  (app) => {
    if (app.hasTable('implementation_checklist')) {
      app.delete(app.findCollectionByNameOrId('implementation_checklist'))
    }
  },
)
